/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental_dvd_deland;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Deland Arjuna Putra
 */
public class Form_Rental extends javax.swing.JFrame {

    /**
     * Creates new form Form_Rental
     */
    private final DefaultTableModel tableModel;
    Object [] data = new Object[4];
    String Nama,Kelas,Cita2,TTL,Hobi,JK,alamat,nohp;
    public Form_Rental() {
        initComponents();
        setLocationRelativeTo(null);
        
        tableModel =(DefaultTableModel) Tabledata.getModel();
        tanggal();
        txtcd.requestFocus();
    }

    public void tanggal(){
        Date skrng = new Date();
        DateFormat tgl =new SimpleDateFormat("dd/MM/yyyy");
        String tanggal = tgl.format(skrng);
        txtpinjam.setText(tanggal);
        String kode = "TRS" + tanggal;
        txttransaksi.setText(kode);
    }
    
    public void inputtanggal(){
        try{
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            format.setLenient(false) ;
            Date date = format.parse(txtkembali.getText());
            
            Date tglpinjam = format.parse(txtkembali.getText());
            Date tglkembali = format.parse(txtpinjam.getText());
            
            long awal = tglpinjam.getTime();
            long akhir = tglkembali.getTime();
            long lama;
            lama = awal-akhir;
            
            long lama2 = TimeUnit.MILLISECONDS.toDays(lama);
            txtlama.setText(String.valueOf(lama2));
        }
        catch(ParseException ex){
            JOptionPane.showMessageDialog(null, "Masukan Tanggal Sesuai " + "Format dd/mm/yyyy", "Pesan Error", JOptionPane.INFORMATION_MESSAGE);
            txtkembali.setText("");
            txtkembali.requestFocus();
        }
    }
    
    public void inputdenda(){
        int lama =Integer.parseInt(txtlama.getText());
        if (lama >= 5 && lama <=10){
            txtdenda.setText(Integer.toString(2500));
        }else if (lama >=10 && lama <=15){
             txtdenda.setText(Integer.toString(5000));
        }else{
            
        }
    }
    
    public void tambah(){
        data[0]=txtcd.getText();
        data[1]=txtjenis.getText();
        data[2]=txtjudul.getText();
        data[3]=txtsewa.getText();
        tableModel.addRow(data);
        kosong();
    }
    
    public void kosong() {
        txtcd.setText("");
        txtjenis.setText("");
        txtjudul.setText("");
        txtsewa.setText("");
        txtcd.requestFocus();
    }    
    
    public void tampil() {
        String notrans = txttransaksi.getText();
        labelno.setText(notrans);
        String nama = txtpelanggan.getText();
        labelnama.setText(nama);
        String ktp = txtktp.getText();
        labelktp.setText(ktp);
        String kembali = txtkembali.getText();
        labelkembali.setText(kembali);
        String pinjam = txtpinjam.getText();
        labelpinjam.setText(pinjam);
        String lama = txtlama.getText();
        labellama.setText(lama);
        String deposit = txtdepo.getText();
        labeldeposit.setText(deposit);
        String denda = txtdenda.getText();
        labeldenda.setText(denda);
        String harga = txttotal.getText();
        labelharga.setText(pinjam);
        
        judul.setText("Data Rental DVD " + nama);
    }
    
    public void Clear(){
        labelno.setText("");
        labelnama.setText("");
        labelktp.setText("");
        labelkembali.setText("");
        labelpinjam.setText("");
        labellama.setText("");
        labeldeposit.setText("");
        labeldenda.setText("");
        labelharga.setText("");
        TextArea.setText("");
        
        judul.setText("Data Rental CD/DVD");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContainerPanel = new javax.swing.JPanel();
        MainTab = new javax.swing.JTabbedPane();
        Tab1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        labelno = new javax.swing.JLabel();
        labelnama = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelktp = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labelkembali = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelpinjam = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        labellama = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labeldeposit = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        labeldenda = new javax.swing.JLabel();
        Denda = new javax.swing.JLabel();
        labelharga = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        Harga1 = new javax.swing.JLabel();
        bexit1 = new javax.swing.JButton();
        Tab2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txttransaksi = new javax.swing.JTextField();
        txtpelanggan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtktp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpinjam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtkembali = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtlama = new javax.swing.JTextField();
        txtdenda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdepo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bproses = new javax.swing.JButton();
        bpreview = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtcd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtjenis = new javax.swing.JTextField();
        txtjudul = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtsewa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabledata = new javax.swing.JTable();
        bexit = new javax.swing.JButton();
        bsimpandata = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainTab.setBackground(new java.awt.Color(255, 255, 255));
        MainTab.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        Tab1.setBackground(new java.awt.Color(255, 255, 255));

        judul.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(51, 51, 255));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("Data Rental D");
        judul.setPreferredSize(new java.awt.Dimension(272, 40));

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Nama Lengkap");

        labelno.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelno.setForeground(new java.awt.Color(51, 51, 255));
        labelno.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 51, 51)));

        labelnama.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelnama.setForeground(new java.awt.Color(51, 51, 255));
        labelnama.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 51, 51)));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Nomor Transaksi");

        labelktp.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelktp.setForeground(new java.awt.Color(51, 51, 255));
        labelktp.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 51, 51)));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("No. KTP");

        labelkembali.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelkembali.setForeground(new java.awt.Color(51, 51, 255));
        labelkembali.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 51, 51)));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Tanggal Kembali");

        labelpinjam.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelpinjam.setForeground(new java.awt.Color(51, 51, 255));
        labelpinjam.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 51, 51)));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Tanggal Pinjam");

        labellama.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labellama.setForeground(new java.awt.Color(51, 51, 255));
        labellama.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 51, 51)));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Lama Pinjam");

        labeldeposit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labeldeposit.setForeground(new java.awt.Color(51, 51, 255));
        labeldeposit.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 51, 51)));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Deposito");

        labeldenda.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labeldenda.setForeground(new java.awt.Color(51, 51, 255));
        labeldenda.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 51, 51)));

        Denda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Denda.setText("Denda");

        labelharga.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        labelharga.setForeground(new java.awt.Color(51, 51, 255));
        labelharga.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 51, 51)));

        Harga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Harga.setText("Harga");

        Harga1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Harga1.setText("Data DVD");

        bexit1.setBackground(new java.awt.Color(255, 0, 51));
        bexit1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bexit1.setForeground(new java.awt.Color(255, 255, 255));
        bexit1.setText("Clear");
        bexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Tab1Layout = new javax.swing.GroupLayout(Tab1);
        Tab1.setLayout(Tab1Layout);
        Tab1Layout.setHorizontalGroup(
            Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bexit1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(judul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Tab1Layout.createSequentialGroup()
                            .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Denda, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(Harga1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(296, 296, 296)
                            .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelktp, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                                .addComponent(labelkembali, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                                .addComponent(labelpinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                                .addComponent(labellama, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                                .addComponent(labeldeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                                .addComponent(labeldenda, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                                .addComponent(labelharga, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Tab1Layout.setVerticalGroup(
            Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelnama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelktp, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelkembali, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labellama, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labeldeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labeldenda, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(Denda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelharga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(Harga1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bexit1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        MainTab.addTab("Detail Rental", Tab1);

        Tab2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("No. Transaksi");

        txttransaksi.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txttransaksi.setForeground(new java.awt.Color(0, 80, 197));
        txttransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txttransaksi.setCaretColor(new java.awt.Color(93, 95, 239));
        txttransaksi.setDisabledTextColor(new java.awt.Color(93, 95, 239));

        txtpelanggan.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtpelanggan.setForeground(new java.awt.Color(0, 80, 197));
        txtpelanggan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtpelanggan.setCaretColor(new java.awt.Color(93, 95, 239));
        txtpelanggan.setDisabledTextColor(new java.awt.Color(93, 95, 239));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Nama Pelanggan");

        txtktp.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtktp.setForeground(new java.awt.Color(0, 80, 197));
        txtktp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtktp.setCaretColor(new java.awt.Color(93, 95, 239));
        txtktp.setDisabledTextColor(new java.awt.Color(93, 95, 239));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("No KTP");

        txtpinjam.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtpinjam.setForeground(new java.awt.Color(0, 80, 197));
        txtpinjam.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtpinjam.setCaretColor(new java.awt.Color(93, 95, 239));
        txtpinjam.setDisabledTextColor(new java.awt.Color(93, 95, 239));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal Pinjam");

        txtkembali.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtkembali.setForeground(new java.awt.Color(0, 80, 197));
        txtkembali.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtkembali.setCaretColor(new java.awt.Color(93, 95, 239));
        txtkembali.setDisabledTextColor(new java.awt.Color(93, 95, 239));
        txtkembali.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtkembaliFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Tanggal Kembali");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Lama");

        txtlama.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtlama.setForeground(new java.awt.Color(0, 80, 197));
        txtlama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtlama.setCaretColor(new java.awt.Color(93, 95, 239));
        txtlama.setDisabledTextColor(new java.awt.Color(93, 95, 239));

        txtdenda.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtdenda.setForeground(new java.awt.Color(0, 80, 197));
        txtdenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtdenda.setCaretColor(new java.awt.Color(93, 95, 239));
        txtdenda.setDisabledTextColor(new java.awt.Color(93, 95, 239));
        txtdenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdendaFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Denda");

        txtdepo.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtdepo.setForeground(new java.awt.Color(0, 80, 197));
        txtdepo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtdepo.setCaretColor(new java.awt.Color(93, 95, 239));
        txtdepo.setDisabledTextColor(new java.awt.Color(93, 95, 239));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Deposito");

        txttotal.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txttotal.setForeground(new java.awt.Color(0, 80, 197));
        txttotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txttotal.setCaretColor(new java.awt.Color(93, 95, 239));
        txttotal.setDisabledTextColor(new java.awt.Color(93, 95, 239));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Total Harga");

        bproses.setBackground(new java.awt.Color(0, 80, 197));
        bproses.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bproses.setForeground(new java.awt.Color(255, 255, 255));
        bproses.setText("Proses");
        bproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprosesActionPerformed(evt);
            }
        });

        bpreview.setBackground(new java.awt.Color(255, 0, 51));
        bpreview.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bpreview.setForeground(new java.awt.Color(255, 255, 255));
        bpreview.setText("Preview");
        bpreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpreviewActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("No. Cewe");

        txtcd.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtcd.setForeground(new java.awt.Color(0, 80, 197));
        txtcd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtcd.setCaretColor(new java.awt.Color(93, 95, 239));
        txtcd.setDisabledTextColor(new java.awt.Color(93, 95, 239));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setText("Jenis Cewe");

        txtjenis.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtjenis.setForeground(new java.awt.Color(0, 80, 197));
        txtjenis.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtjenis.setCaretColor(new java.awt.Color(93, 95, 239));
        txtjenis.setDisabledTextColor(new java.awt.Color(93, 95, 239));

        txtjudul.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtjudul.setForeground(new java.awt.Color(0, 80, 197));
        txtjudul.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtjudul.setCaretColor(new java.awt.Color(93, 95, 239));
        txtjudul.setDisabledTextColor(new java.awt.Color(93, 95, 239));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("Nama Cewe");

        txtsewa.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        txtsewa.setForeground(new java.awt.Color(0, 80, 197));
        txtsewa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtsewa.setCaretColor(new java.awt.Color(93, 95, 239));
        txtsewa.setDisabledTextColor(new java.awt.Color(93, 95, 239));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setText("Harga Sewa");

        Tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO CEWE", "JENIS CEWE", "NAMA CEWE", "HARGA SEWA"
            }
        ));
        Tabledata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabledataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabledata);
        if (Tabledata.getColumnModel().getColumnCount() > 0) {
            Tabledata.getColumnModel().getColumn(3).setResizable(false);
        }

        bexit.setBackground(new java.awt.Color(255, 0, 51));
        bexit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bexit.setForeground(new java.awt.Color(255, 255, 255));
        bexit.setText("Exit");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        bsimpandata.setBackground(new java.awt.Color(0, 80, 197));
        bsimpandata.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bsimpandata.setForeground(new java.awt.Color(255, 255, 255));
        bsimpandata.setText("Simpan");
        bsimpandata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpandataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Tab2Layout = new javax.swing.GroupLayout(Tab2);
        Tab2.setLayout(Tab2Layout);
        Tab2Layout.setHorizontalGroup(
            Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab2Layout.createSequentialGroup()
                        .addComponent(txtdepo)
                        .addGap(26, 26, 26))
                    .addGroup(Tab2Layout.createSequentialGroup()
                        .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtdenda)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Tab2Layout.createSequentialGroup()
                                    .addComponent(bproses, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bpreview, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtkembali, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtpinjam, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtpelanggan, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtktp, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txttransaksi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtlama, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                        .addComponent(txtsewa)
                        .addComponent(txtjudul)
                        .addComponent(txtjenis)
                        .addComponent(txtcd)
                        .addComponent(bsimpandata, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        Tab2Layout.setVerticalGroup(
            Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Tab2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Tab2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Tab2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtktp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Tab2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Tab2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsewa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtlama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdenda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdepo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tab2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bsimpandata, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(Tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bproses, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpreview, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        MainTab.addTab("Form Rental", Tab2);

        javax.swing.GroupLayout ContainerPanelLayout = new javax.swing.GroupLayout(ContainerPanel);
        ContainerPanel.setLayout(ContainerPanelLayout);
        ContainerPanelLayout.setHorizontalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTab)
        );
        ContainerPanelLayout.setVerticalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTab)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprosesActionPerformed
        // TODO add your handling code here:
        int total = 0;
        int deposit, denda, lama;
        deposit = Integer.parseInt(txtdepo.getText());
        denda = Integer.parseInt(txtdenda.getText());
        lama = Integer.parseInt(txtlama.getText());
        for (int i=0; i<Tabledata.getRowCount(); i++){
            int sewa = Integer.parseInt((String) Tabledata.getValueAt(i, 3));
            if (lama >= 5){
                
                denda = 5000;
            }
            total = ((total + (sewa*lama)+denda) - deposit);
            txttotal.setText(String.valueOf(total));
            String AA = Tabledata.getValueAt(i, 0) + "\t\t" + Tabledata.getValueAt(i, 3) + "\n";
            TextArea.append(AA);
        }
    }//GEN-LAST:event_bprosesActionPerformed

    private void bpreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpreviewActionPerformed
        // TODO add your handling code here:
        MainTab.setSelectedIndex(0);
        tampil();
    }//GEN-LAST:event_bpreviewActionPerformed

    private void TabledataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabledataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TabledataMouseClicked

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bexitActionPerformed

    private void bsimpandataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpandataActionPerformed
        // TODO add your handling code here:
        if(txtcd.getText().equals("") || txtsewa.getText().equals("") || txtjenis.getText().equals("") || txtjudul.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data Masih Kosong");
            txtcd.requestFocus();
        }else{
            tambah();
        }
    }//GEN-LAST:event_bsimpandataActionPerformed

    private void txtkembaliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkembaliFocusLost
        // TODO add your handling code here:
        inputtanggal();
    }//GEN-LAST:event_txtkembaliFocusLost

    private void txtdendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdendaFocusLost
        // TODO add your handling code here:
        inputdenda();
    }//GEN-LAST:event_txtdendaFocusLost

    private void bexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexit1ActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_bexit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Rental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContainerPanel;
    private javax.swing.JLabel Denda;
    private javax.swing.JLabel Harga;
    private javax.swing.JLabel Harga1;
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JPanel Tab1;
    private javax.swing.JPanel Tab2;
    private javax.swing.JTable Tabledata;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton bexit;
    private javax.swing.JButton bexit1;
    private javax.swing.JButton bpreview;
    private javax.swing.JButton bproses;
    private javax.swing.JButton bsimpandata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel labeldenda;
    private javax.swing.JLabel labeldeposit;
    private javax.swing.JLabel labelharga;
    private javax.swing.JLabel labelkembali;
    private javax.swing.JLabel labelktp;
    private javax.swing.JLabel labellama;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labelno;
    private javax.swing.JLabel labelpinjam;
    private javax.swing.JTextField txtcd;
    private javax.swing.JTextField txtdenda;
    private javax.swing.JTextField txtdepo;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtkembali;
    private javax.swing.JTextField txtktp;
    private javax.swing.JTextField txtlama;
    private javax.swing.JTextField txtpelanggan;
    private javax.swing.JTextField txtpinjam;
    private javax.swing.JTextField txtsewa;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttransaksi;
    // End of variables declaration//GEN-END:variables
}
